application:
    name: movie-app
    cors:
      allowed-origins: ${FRONT_URL}

spring:
  jackson:
    deserialization:
      fail-on-unknown-properties: false

  config:
    import:
      - classpath:database.yml
      - classpath:movie-api.yml
      - optional:file:./.env[.properties]

server:
  port: ${BACKEND_PORT:8080}
  address: ${BACKEND_ADRESS:127.0.0.1}
