spring:
  application:
    name: movie-app
    cors:
      allowed-origins: ${FRONT_URL}

  jackson:
    deserialization:
      fail-on-unknown-properties: false
#    serialization:
#      fail-on-empty-beans: false

  config:
    import:
      - classpath:database.yml
      - classpath:movie-api.yml
      - optional:file:./.env[.properties]

server:
  port: ${PORT:8080}
  address: 0.0.0.0
