spring:
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: ${DRIVER_CLASS_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: true

    properties:
      hibernate:
        format_sql: true
    #        dialect: org.hibernate.dialect.PostgreSQLDialect

    hibernate:
      ddl-auto: update
